// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyR99kOPJLZRckSM5x5YhLEQt0s0SNtdo',
    appId: '1:870439352325:web:908a3056c24bba5de5446c',
    messagingSenderId: '870439352325',
    projectId: 'simple-todo-256ec',
    authDomain: 'simple-todo-256ec.firebaseapp.com',
    storageBucket: 'simple-todo-256ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Kgv49Tmc-wGLD8xHmjQ48Jn6U7Hmcgw',
    appId: '1:870439352325:android:b8ca235ac0ed9d72e5446c',
    messagingSenderId: '870439352325',
    projectId: 'simple-todo-256ec',
    storageBucket: 'simple-todo-256ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Je8R-qSn7hJwOU8KprcpKac-oBdMduM',
    appId: '1:870439352325:ios:46e88beacf00434ee5446c',
    messagingSenderId: '870439352325',
    projectId: 'simple-todo-256ec',
    storageBucket: 'simple-todo-256ec.appspot.com',
    iosClientId: '870439352325-lo94t5bfrmvjfo8narut4tlm3162onn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTodo',
  );
}
